export const VIDEOS = [
  {
    id: "1",
    title: "Building a YouTube Clone with React Native",
    thumbnail: "https://picsum.photos/600/400?1",
    channelName: "Nimsy Official",
    views: "125K views",
    uploadedAt: "2 days ago",
    duration: "12:45",
  },
  {
    id: "2",
    title: "Fastify + Prisma Complete Backend Setup",
    thumbnail: "https://picsum.photos/600/400?2",
    channelName: "Nimsy Official",
    views: "89K views",
    uploadedAt: "5 days ago",
    duration: "18:20",
  },
  {
    id: "3",
    title: "S3 Multipart Upload Explained",
    thumbnail: "https://picsum.photos/600/400?3",
    channelName: "Nimsy Official",
    views: "45K views",
    uploadedAt: "1 week ago",
    duration: "09:12",
  },
  {
    id: "4",
    title: "Build Reels Like Instagram",
    thumbnail: "https://picsum.photos/600/400?4",
    channelName: "Nimsy Official",
    views: "310K views",
    uploadedAt: "2 weeks ago",
    duration: "15:08",
  },
  {
    id: "5",
    title: "React Native Performance Tips",
    thumbnail: "https://picsum.photos/600/400?5",
    channelName: "Nimsy Official",
    views: "67K views",
    uploadedAt: "3 weeks ago",
    duration: "11:30",
  },
];